# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
server:
  port: 8085 
  servlet:
    session:
      cookie:
        name: OAUTH2SESSION # This is to prevent cookie clash with other service as they run on the same host and context path
  
spring:
  application:
    name: auth
  
  #数据库连接配置
  datasource:
    name: auth
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sperm?useUnicode=true&characterEncoding=UTF-8
    username: admin
    password: Passw0rd

    dbcp:
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      min-idle: 1
      max-wait: 60000
      initial-size: 1
      max-active: 20
  
  #redis连接
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    #host: 192.168.1.104
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: admin
    # 超时
    timeout: 0
    # 连接池
    pool: 
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 50
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 40
      # 连接池中的最小空闲连接
      min-idle: 20

mybatis:
  type-aliases-package: com.sky.auth.*.dao
  mapper-locations: classpath*:/mybatis/*.xml
  
#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  

#oauth2 相关配置  
security:
  oauth2:
    # 客户端相关配置	OAuth2ClientProperties
    client:
      clientId: client_1
      clientSecret: 123456
      accessTokenUri: http://127.0.0.1:8087/oauth/token
      userAuthorizationUri: http://127.0.0.1:8087/oauth/authorize
      pre-established-redirect-uri: http://http://127.0.0.1:8085/access-token
    # 资源服务器相关配置  ResourceServerProperties
    resource:
      clientId: client_1
      clientSecret: 123456
      tokenInfoUri: http://127.0.0.1:8087/check_token
    # 认证服务器相关配置
      
      

    